### ISSUE TITLE
Documentation refresh

### ISSUE THREAD

**Issue by longrunningprocess** [apiaxle/website#3]
Information on the recent Qpm and ApiNameRegex additions is missing.

this one too (once it's merged):  https://github.com/apiaxle/apiaxle/pull/95

**Comment by sleepylemur** [comment]
Regenerated api.html from apiaxle/apiaxle#develop, which should cover qpm and additionalHeaders.
ApiNameRegex needs to be documented in [configuration](https://github.com/apiaxle/website/blob/gh-pages/_posts/2013-03-05-configuration.md) if I'm not mistaken.
